version: '3'
services:
  practicum.rails.postgres.db:
    image: postgres
    volumes:
      - /tmp/volumes/database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

  practicum.rails.api:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - practicum.rails.postgres.db
    environment:
      - DATABASE_HOST=practicum.rails.postgres.db
      - DATABASE_PASSWORD=postgres
      - DATABASE_USER=postgres
